# Generated by Django 3.2.3 on 2023-09-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230920_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
