# Generated by Django 3.2.3 on 2023-10-11 13:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20231011_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredients', to='recipes.ingredient', validators=[django.core.validators.MinValueValidator(1, 'Рецепт не может быть без ингредиента!')], verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredients', to='recipes.recipe', validators=[django.core.validators.MinValueValidator(1, 'Рецепт не может быть без ингредиента!')], verbose_name='Рецепт'),
        ),
    ]
