# Generated by Django 3.2.3 on 2023-10-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['user'], 'verbose_name': 'Мои подписки', 'verbose_name_plural': 'Мои подписки'},
        ),
    ]
